import js from '@eslint/js';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import prettier from 'eslint-plugin-prettier';
import jsdocPlugin from 'eslint-plugin-jsdoc';
import importPlugin from 'eslint-plugin-import';

export default [
	// 基础 JavaScript 配置
	js.configs.recommended,

	// 全局变量配置
	{
		files: ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx'],
	},

	// TypeScript 配置
	{
		files: ['**/*.ts', '**/*.tsx'],
		languageOptions: {
			parser: typescriptParser,
			parserOptions: {
				ecmaVersion: 2021,
				sourceType: 'module',
				ecmaFeatures: {
					jsx: true
				}
			}
		},
		plugins: {
			'@typescript-eslint': typescriptEslint,
			'prettier': prettier,
			'jsdoc': jsdocPlugin,
			'import': importPlugin
		},
		rules: {
			// 启用 TypeScript 的类型检查规则
			'@typescript-eslint/no-unused-vars': 'off',
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/explicit-function-return-type': 'off',
			'@typescript-eslint/explicit-module-boundary-types': 'off',
			'@typescript-eslint/no-inferrable-types': 'off',
			'@typescript-eslint/prefer-namespace-keyword': 'error',
			'@typescript-eslint/triple-slash-reference': 'error',

			// 禁用基础规则，使用 TypeScript 版本
			'no-undef': 'off',
			'no-unused-vars': 'off',
			'@typescript-eslint/no-redeclare': 'error',

			// 属性顺序规则
			'@typescript-eslint/member-ordering': 'error',

			// 其他规则保持不变...
			'no-cond-assign': 'error',
			'no-console': 'off',
			'no-constant-condition': 'error',
			'no-control-regex': 'error',
			'comma-dangle': ['off', 'always-multiline'],
			'no-debugger': 'error',
			'no-dupe-args': 'error',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-empty': 'error',
			'no-empty-character-class': 'error',
			'no-ex-assign': 'error',
			'no-extra-boolean-cast': 'error',
			'no-extra-parens': 'off',
			'no-extra-semi': 'off',
			'no-func-assign': 'error',
			'no-inner-declarations': ['error', 'functions'],
			'no-invalid-regexp': 'error',
			'no-irregular-whitespace': 'error',
			'no-negated-in-lhs': 'error',
			'no-obj-calls': 'error',
			'no-prototype-builtins': 'off',
			'no-regex-spaces': 'error',
			'no-sparse-arrays': 'error',
			'no-unexpected-multiline': 'error',
			'no-unreachable': 'error',
			'use-isnan': 'error',
			'valid-typeof': 'error',

			// 最佳实践
			'accessor-pairs': 'error',
			'array-callback-return': 'off',
			'block-scoped-var': 'off',
			'complexity': ['error', 20],
			'consistent-return': 'off',
			'curly': ['error', 'all'],
			'default-case': 'error',
			'dot-location': ['error', 'property'],
			'dot-notation': ['off', { 'allowKeywords': false }],
			'eqeqeq': ['error', 'allow-null'],
			'guard-for-in': 'off',
			'no-alert': 'off',
			'no-caller': 'error',
			'no-case-declarations': 'off',
			'no-div-regex': 'error',
			'no-else-return': 'off',
			'no-empty-function': 'off',
			'no-empty-pattern': 'error',
			'no-eq-null': 'warn',
			'no-eval': 'error',
			'no-extend-native': 'error',
			'no-extra-bind': 'error',
			'no-fallthrough': 'error',
			'no-floating-decimal': 'error',
			'no-implicit-coercion': 'off',
			'no-implicit-globals': 'off',
			'no-implied-eval': 'error',
			'no-invalid-this': 'off',
			'no-iterator': 'error',
			'no-labels': 'error',
			'no-lone-blocks': 'error',
			'no-loop-func': 'off',
			'no-magic-numbers': ['off', { 'ignore': [0, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9] }],
			'no-multi-spaces': 'error',
			'no-multi-str': 'error',
			'no-new': 'error',
			'no-new-func': 'off',
			'no-new-wrappers': 'error',
			'no-octal': 'error',
			'no-octal-escape': 'error',
			'no-param-reassign': 'off',
			'no-proto': 'error',
			'no-redeclare': 'off',
			'no-return-assign': 'off',
			'no-script-url': 'off',
			'no-self-assign': 'error',
			'no-self-compare': 'error',
			'no-sequences': 'error',
			'no-throw-literal': 'error',
			'no-unmodified-loop-condition': 'error',
			'no-unused-expressions': 'off',
			'no-unused-labels': 'error',
			'no-useless-call': 'off',
			'no-useless-concat': 'error',
			'no-useless-escape': 'off',
			'no-void': 'off',
			'no-warning-comments': 'off',
			'no-with': 'error',
			'radix': 'error',
			'vars-on-top': 'off',
			'wrap-iife': ['error', 'any'],
			'yoda': ['error', 'never'],

			// 变量声明 - 使用 TypeScript 版本
			'init-declarations': 'off',
			'no-catch-shadow': 'off',
			'no-delete-var': 'error',
			'no-label-var': 'error',
			'no-restricted-globals': 'off',
			'no-shadow': 'off',
			'no-shadow-restricted-names': 'error',
			'no-undef-init': 'error',
			'no-undefined': 'off',
			'no-use-before-define': 'off',

			// Node.js and CommonJS
			'callback-return': 'off',
			'global-require': 'warn',
			'handle-callback-err': ['error', '^(err|error)$'],
			'no-mixed-requires': 'off',
			'no-new-require': 'error',
			'no-path-concat': 'off',
			'no-process-env': 'off',
			'no-process-exit': 'off',
			'no-sync': 'off',

			// 风格指南
			'array-bracket-spacing': ['error', 'never'],
			'block-spacing': ['warn', 'never'],
			'brace-style': ['off', '1tbs', { 'allowSingleLine': false }],
			'camelcase': 'off',
			'comma-spacing': ['error', { 'before': false, 'after': true }],
			'comma-style': ['error', 'last'],
			'computed-property-spacing': ['error', 'never'],
			'consistent-this': ['warn', 'that'],
			'func-names': 'off',
			'eol-last': 'error',
			'indent': ['off', 4, { 'SwitchCase': 1 }],
			'key-spacing': ['error', { 'beforeColon': false, 'afterColon': true }],
			'linebreak-style': ['warn', 'unix'],
			'lines-around-comment': ['off', { 'beforeBlockComment': true }],
			'func-style': 'off',
			'max-nested-callbacks': ['warn', 5],
			'id-blacklist': 'off',
			'id-length': 'off',
			'id-match': 'off',
			'jsx-quotes': 'off',
			'keyword-spacing': 'error',
			'max-len': ['warn', 200],
			'max-lines': 'off',
			'max-params': ['warn', 8],
			'max-statements': ['warn', 200],
			'max-statements-per-line': 'off',
			'new-cap': ['off', { 'newIsCap': true, 'capIsNew': false }],
			'new-parens': 'error',
			'newline-after-var': 'off',
			'no-array-constructor': 'error',
			'no-bitwise': 'off',
			'newline-before-return': 'off',
			'newline-per-chained-call': 'warn',
			'no-continue': 'off',
			'no-inline-comments': 'off',
			'no-lonely-if': 'off',
			'no-mixed-operators': 'off',
			'no-mixed-spaces-and-tabs': 'error',
			'no-multiple-empty-lines': ['error', { 'max': 2 }],
			'no-negated-condition': 'off',
			'no-nested-ternary': 'off',
			'no-new-object': 'error',
			'no-plusplus': 'off',
			'no-restricted-syntax': 'off',
			'no-ternary': 'off',
			'no-trailing-spaces': 'error',
			'no-underscore-dangle': 'off',
			'no-unneeded-ternary': 'error',
			'no-whitespace-before-property': 'off',
			'object-curly-newline': 'off',
			'object-curly-spacing': 'off',
			'object-property-newline': 'off',
			'one-var': ['error', { 'initialized': 'never' }],
			'one-var-declaration-per-line': 'off',
			'operator-assignment': 'off',
			'operator-linebreak': ['error', 'after', { 'overrides': { '?': 'before', ':': 'before' } }],
			'padded-blocks': 'off',
			'quote-props': 'off',
			'quotes': ['off', 'single', 'avoid-escape'],
			'jsdoc/require-jsdoc': 'warn',
			'jsdoc/check-param-names': 'warn',
			'jsdoc/check-tag-names': 'warn',
			'jsdoc/check-types': 'warn',
			'semi': ['error', 'always'],
			'semi-spacing': 'off',
			'sort-vars': 'off',
			'space-before-blocks': ['error', 'always'],
			'space-before-function-paren': ['off', 'always'],
			'space-in-parens': ['error', 'never'],
			'space-infix-ops': 'error',
			'space-unary-ops': ['error', { 'words': true, 'nonwords': false }],
			'spaced-comment': ['off', 'always', { 'markers': ['global', 'globals', 'eslint', 'eslint-disable', '*package', '!'] }],
			'unicode-bom': 'off',
			'wrap-regex': 'off',

			// ES6相关
			'arrow-body-style': 'off',
			'arrow-parens': 'error',
			'arrow-spacing': ['error', { 'before': true, 'after': true }],
			'constructor-super': 'off',
			'generator-star-spacing': ['error', { 'before': true, 'after': true }],
			'no-class-assign': 'error',
			'no-confusing-arrow': 'off',
			'no-const-assign': 'error',
			'no-dupe-class-members': 'error',
			'no-duplicate-imports': 'off',
			'no-new-symbol': 'error',
			'no-restricted-imports': 'off',
			'no-this-before-super': 'error',
			'no-useless-computed-key': 'off',
			'no-var': 'off',
			'object-shorthand': 'off',
			'prefer-arrow-callback': 'off',
			'prefer-const': 'warn',
			'prefer-reflect': 'off',
			'prefer-spread': 'off',
			'prefer-template': 'off',
			'prefer-rest-params': 'off',
			'require-yield': 'off',
			'rest-spread-spacing': 'off',
			'sort-imports': 'off',
			'template-curly-spacing': 'warn',
			'yield-star-spacing': 'error',
		}
	},
	{
		ignores: [
			'node_modules/',
			'src/luban/',
			'release/',
			'libs/',
			'build/'
		]
	}
];
